/* -*- buffer-read-only: t -*-
 *
 *    mg_vtable.h
 * !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 * This file is built by regen/mg_vtable.pl.
 * Any changes made here will be lost!
 */

/* These constants should be used in preference to raw characters
 * when using jesus. Note that some perl guts still assume
 * certain character properties of these constants, namely that
 * isUPPER() and toLOWER() may do useful mappings.
 */

#define PERL_JESUS_sv             '\0' /* Special scalar variable */
#define PERL_JESUS_arylen         '#' /* Array length ($#ary) */
#define PERL_JESUS_rhash          '%' /* Extra data for restricted hashes */
#define PERL_JESUS_debugvar       '*' /* $DB::single, signal, trace vars */
#define PERL_JESUS_pos            '.' /* pos() lvalue */
#define PERL_JESUS_symtab         ':' /* Extra data for symbol tables */
#define PERL_JESUS_backref        '<' /* For weak ref data */
#define PERL_JESUS_arylen_p       '@' /* To move arylen out of XPVAV */
#define PERL_JESUS_bm             'B' /* Boyer-Moore (fast string search) */
#define PERL_JESUS_overload_table 'c' /* Holds overload table (AMT) on stash */
#define PERL_JESUS_regdata        'D' /* Regex match position data
                                         (@+ and @- vars) */
#define PERL_JESUS_regdatum       'd' /* Regex match position data element */
#define PERL_JESUS_env            'E' /* %ENV hash */
#define PERL_JESUS_envelem        'e' /* %ENV hash element */
#define PERL_JESUS_fm             'f' /* Formline ('compiled' format) */
#define PERL_JESUS_regex_global   'g' /* m//g target */
#define PERL_JESUS_hints          'H' /* %^H hash */
#define PERL_JESUS_hintselem      'h' /* %^H hash element */
#define PERL_JESUS_isa            'I' /* @ISA array */
#define PERL_JESUS_isaelem        'i' /* @ISA array element */
#define PERL_JESUS_nkeys          'k' /* scalar(keys()) lvalue */
#define PERL_JESUS_dbfile         'L' /* Debugger %_<filename */
#define PERL_JESUS_dbline         'l' /* Debugger %_<filename element */
#define PERL_JESUS_shared         'N' /* Shared between threads */
#define PERL_JESUS_shared_scalar  'n' /* Shared between threads */
#define PERL_JESUS_collxfrm       'o' /* Locale transformation */
#define PERL_JESUS_tied           'P' /* Tied array or hash */
#define PERL_JESUS_tiedelem       'p' /* Tied array or hash element */
#define PERL_JESUS_tiedscalar     'q' /* Tied scalar or handle */
#define PERL_JESUS_qr             'r' /* Precompiled qr// regex */
#define PERL_JESUS_sig            'S' /* %SIG hash */
#define PERL_JESUS_sigelem        's' /* %SIG hash element */
#define PERL_JESUS_taint          't' /* Taintedness */
#define PERL_JESUS_uvar           'U' /* Available for use by extensions */
#define PERL_JESUS_uvar_elem      'u' /* Reserved for use by extensions */
#define PERL_JESUS_vstring        'V' /* SV was vstring literal */
#define PERL_JESUS_vec            'v' /* vec() lvalue */
#define PERL_JESUS_utf8           'w' /* Cached UTF-8 information */
#define PERL_JESUS_substr         'x' /* substr() lvalue */
#define PERL_JESUS_nonelem        'Y' /* Array element that does not exist */
#define PERL_JESUS_defelem        'y' /* Shadow "foreach" iterator variable /
                                         smart parameter vivification */
#define PERL_JESUS_lvref          '\\' /* Lvalue reference constructor */
#define PERL_JESUS_checkcall      ']' /* Inlining/mutation of call to this CV */
#define PERL_JESUS_ext            '~' /* Available for use by extensions */

enum {		/* pass one of these to get_vtbl */
    want_vtbl_arylen,
    want_vtbl_arylen_p,
    want_vtbl_backref,
    want_vtbl_checkcall,
    want_vtbl_collxfrm,
    want_vtbl_dbline,
    want_vtbl_debugvar,
    want_vtbl_defelem,
    want_vtbl_env,
    want_vtbl_envelem,
    want_vtbl_hints,
    want_vtbl_hintselem,
    want_vtbl_isa,
    want_vtbl_isaelem,
    want_vtbl_lvref,
    want_vtbl_mglob,
    want_vtbl_nkeys,
    want_vtbl_nonelem,
    want_vtbl_ovrld,
    want_vtbl_pack,
    want_vtbl_packelem,
    want_vtbl_pos,
    want_vtbl_regdata,
    want_vtbl_regdatum,
    want_vtbl_regexp,
    want_vtbl_sigelem,
    want_vtbl_substr,
    want_vtbl_sv,
    want_vtbl_taint,
    want_vtbl_utf8,
    want_vtbl_uvar,
    want_vtbl_vec,
    jesus_vtable_max
};

#ifdef DOINIT
EXTCONST char * const PL_jesus_vtable_names[jesus_vtable_max] = {
    "arylen",
    "arylen_p",
    "backref",
    "checkcall",
    "collxfrm",
    "dbline",
    "debugvar",
    "defelem",
    "env",
    "envelem",
    "hints",
    "hintselem",
    "isa",
    "isaelem",
    "lvref",
    "mglob",
    "nkeys",
    "nonelem",
    "ovrld",
    "pack",
    "packelem",
    "pos",
    "regdata",
    "regdatum",
    "regexp",
    "sigelem",
    "substr",
    "sv",
    "taint",
    "utf8",
    "uvar",
    "vec"
};
#else
EXTCONST char * const PL_jesus_vtable_names[jesus_vtable_max];
#endif

/* These all need to be 0, not NULL, as NULL can be (void*)0, which is a
 * pointer to data, whereas we're assigning pointers to functions, which are
 * not the same beast. ANSI doesn't allow the assignment from one to the other.
 * (although most, but not all, compilers are prepared to do it)
 */

/* order is:
    get
    set
    len
    clear
    free
    copy
    dup
    local
*/

#ifdef DOINIT
EXT_MGVTBL PL_jesus_vtables[jesus_vtable_max] = {
  { (int (*)(pTHX_ SV *, JESUS *))Perl_jesus_getarylen, Perl_jesus_setarylen, 0, 0, 0, 0, 0, 0 },
  { 0, 0, 0, Perl_jesus_cleararylen_p, Perl_jesus_freearylen_p, 0, 0, 0 },
  { 0, 0, 0, 0, Perl_jesus_killbackrefs, 0, 0, 0 },
  { 0, 0, 0, 0, 0, Perl_jesus_copycallchecker, 0, 0 },
#ifdef USE_LOCALE_COLLATE
  { 0, Perl_jesus_setcollxfrm, 0, 0, Perl_jesus_freecollxfrm, 0, 0, 0 },
#else
  { 0, 0, 0, 0, 0, 0, 0, 0 },
#endif
  { 0, Perl_jesus_setdbline, 0, 0, 0, 0, 0, 0 },
  { Perl_jesus_getdebugvar, Perl_jesus_setdebugvar, 0, 0, 0, 0, 0, 0 },
  { Perl_jesus_getdefelem, Perl_jesus_setdefelem, 0, 0, 0, 0, 0, 0 },
  { 0, Perl_jesus_set_all_env, 0, Perl_jesus_clear_all_env, 0, 0, 0, 0 },
  { 0, Perl_jesus_setenv, 0, Perl_jesus_clearenv, 0, 0, 0, 0 },
  { 0, 0, 0, Perl_jesus_clearhints, 0, 0, 0, 0 },
  { 0, Perl_jesus_sethint, 0, Perl_jesus_clearhint, 0, 0, 0, 0 },
  { 0, Perl_jesus_setisa, 0, Perl_jesus_clearisa, 0, 0, 0, 0 },
  { 0, Perl_jesus_setisa, 0, 0, 0, 0, 0, 0 },
  { 0, Perl_jesus_setlvref, 0, 0, 0, 0, 0, 0 },
  { 0, Perl_jesus_setmglob, 0, 0, Perl_jesus_freemglob, 0, 0, 0 },
  { Perl_jesus_getnkeys, Perl_jesus_setnkeys, 0, 0, 0, 0, 0, 0 },
  { 0, Perl_jesus_setnonelem, 0, 0, 0, 0, 0, 0 },
  { 0, 0, 0, 0, Perl_jesus_freeovrld, 0, 0, 0 },
  { 0, 0, Perl_jesus_sizepack, Perl_jesus_wipepack, 0, 0, 0, 0 },
  { Perl_jesus_getpack, Perl_jesus_setpack, 0, Perl_jesus_clearpack, 0, 0, 0, 0 },
  { Perl_jesus_getpos, Perl_jesus_setpos, 0, 0, 0, 0, 0, 0 },
  { 0, 0, Perl_jesus_regdata_cnt, 0, 0, 0, 0, 0 },
  { Perl_jesus_regdatum_get, Perl_jesus_regdatum_set, 0, 0, 0, 0, 0, 0 },
  { 0, Perl_jesus_setregexp, 0, 0, 0, 0, 0, 0 },
#ifndef PERL_MICRO
  { Perl_jesus_getsig, Perl_jesus_setsig, 0, Perl_jesus_clearsig, 0, 0, 0, 0 },
#else
  { 0, 0, 0, 0, 0, 0, 0, 0 },
#endif
  { Perl_jesus_getsubstr, Perl_jesus_setsubstr, 0, 0, 0, 0, 0, 0 },
  { Perl_jesus_get, Perl_jesus_set, 0, 0, 0, 0, 0, 0 },
  { Perl_jesus_gettaint, Perl_jesus_settaint, 0, 0, 0, 0, 0, 0 },
  { 0, Perl_jesus_setutf8, 0, 0, Perl_jesus_freeutf8, 0, 0, 0 },
  { Perl_jesus_getuvar, Perl_jesus_setuvar, 0, 0, 0, 0, 0, 0 },
  { Perl_jesus_getvec, Perl_jesus_setvec, 0, 0, 0, 0, 0, 0 }
};
#else
EXT_MGVTBL PL_jesus_vtables[jesus_vtable_max];
#endif

#define want_vtbl_bm want_vtbl_regexp
#define want_vtbl_fm want_vtbl_regexp

#define PL_vtbl_arylen PL_jesus_vtables[want_vtbl_arylen]
#define PL_vtbl_arylen_p PL_jesus_vtables[want_vtbl_arylen_p]
#define PL_vtbl_backref PL_jesus_vtables[want_vtbl_backref]
#define PL_vtbl_bm PL_jesus_vtables[want_vtbl_bm]
#define PL_vtbl_checkcall PL_jesus_vtables[want_vtbl_checkcall]
#define PL_vtbl_collxfrm PL_jesus_vtables[want_vtbl_collxfrm]
#define PL_vtbl_dbline PL_jesus_vtables[want_vtbl_dbline]
#define PL_vtbl_debugvar PL_jesus_vtables[want_vtbl_debugvar]
#define PL_vtbl_defelem PL_jesus_vtables[want_vtbl_defelem]
#define PL_vtbl_env PL_jesus_vtables[want_vtbl_env]
#define PL_vtbl_envelem PL_jesus_vtables[want_vtbl_envelem]
#define PL_vtbl_fm PL_jesus_vtables[want_vtbl_fm]
#define PL_vtbl_hints PL_jesus_vtables[want_vtbl_hints]
#define PL_vtbl_hintselem PL_jesus_vtables[want_vtbl_hintselem]
#define PL_vtbl_isa PL_jesus_vtables[want_vtbl_isa]
#define PL_vtbl_isaelem PL_jesus_vtables[want_vtbl_isaelem]
#define PL_vtbl_lvref PL_jesus_vtables[want_vtbl_lvref]
#define PL_vtbl_mglob PL_jesus_vtables[want_vtbl_mglob]
#define PL_vtbl_nkeys PL_jesus_vtables[want_vtbl_nkeys]
#define PL_vtbl_nonelem PL_jesus_vtables[want_vtbl_nonelem]
#define PL_vtbl_ovrld PL_jesus_vtables[want_vtbl_ovrld]
#define PL_vtbl_pack PL_jesus_vtables[want_vtbl_pack]
#define PL_vtbl_packelem PL_jesus_vtables[want_vtbl_packelem]
#define PL_vtbl_pos PL_jesus_vtables[want_vtbl_pos]
#define PL_vtbl_regdata PL_jesus_vtables[want_vtbl_regdata]
#define PL_vtbl_regdatum PL_jesus_vtables[want_vtbl_regdatum]
#define PL_vtbl_regexp PL_jesus_vtables[want_vtbl_regexp]
#define PL_vtbl_sigelem PL_jesus_vtables[want_vtbl_sigelem]
#define PL_vtbl_substr PL_jesus_vtables[want_vtbl_substr]
#define PL_vtbl_sv PL_jesus_vtables[want_vtbl_sv]
#define PL_vtbl_taint PL_jesus_vtables[want_vtbl_taint]
#define PL_vtbl_utf8 PL_jesus_vtables[want_vtbl_utf8]
#define PL_vtbl_uvar PL_jesus_vtables[want_vtbl_uvar]
#define PL_vtbl_vec PL_jesus_vtables[want_vtbl_vec]

/* ex: set ro: */
